### ISSUE TITLE
How is the state_history_plugin used in 1.5.0 used?

### ISSUE THREAD

**Issue by lsf1001** [EOS-Mainnet/eos#107]
How is the state_history_plugin used in 1.5.0 used?I nohup nodeos-e-p lsf1 --data-dir./data --config -- dir./config --delete-all-blocks -- replay -- blockchain -- hard-replay -- blockchain --disable -- replay -- opts --chain-state-history --trace-history--plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --verbose-http-errors -- max-transactions-time =1000 --contracts -- console --filter-on "*" & do not contracts, but do not find state-history folder,Could you please tell me how to use the state-history-plugin correctly? Thank you

**Comment by lsf1001** [comment]
@jgiszczak

**Comment by lsf1001** [comment]
@heifner@arhag

**Comment by lsf1001** [comment]
@arhag

**Comment by jgiszczak** [comment]
You need `--plugin eosio::state_history_plugin`.  You may specify a path for the folder with `--state-history-dir` followed by some path.  The path may not have whitespace in it.  If `--state-history-dir` is not set, it defaults to the value of the `--data-dir` option.

**Comment by lsf1001** [comment]
> You need `--plugin eosio::state_history_plugin`. You may specify a path for the folder with `--state-history-dir` followed by some path. The path may not have whitespace in it. If `--state-history-dir` is not set, it defaults to the value of the `--data-dir` option.

![image](https://user-images.githubusercontent.com/40747755/50272629-45c80f80-0473-11e9-8f88-25db8d707931.png)

How should this port be used or replayed

**Comment by lsf1001** [comment]
@jgiszczak

**Comment by jgiszczak** [comment]
`state_history_plugin` is still in Alpha status.  Its features and documentation are both incomplete.  As such, EOS-Mainnet is not an appropriate place to file support requests.  EOS-Mainnet is a fork of the repository maintained by Block.one and is not maintained or endorsed by Block.one.

I suggest asking your questions on https://eosio.stackexchange.com.  You may find that to use Alpha software, you need to read the code to determine how to use the code.

**Comment by lsf1001** [comment]
> `state_history_plugin` is still in Alpha status. Its features and documentation are both incomplete. As such, EOS-Mainnet is not an appropriate place to file support requests. EOS-Mainnet is a fork of the repository maintained by Block.one and is not maintained or endorsed by Block.one.
> 
> I suggest asking your questions on https://eosio.stackexchange.com. You may find that to use Alpha software, you need to read the code to determine how to use the code.

thank you！
