### ISSUE TITLE
1.5.x eosio.sudo ？

### ISSUE THREAD

**Issue by lsf1001** [EOS-Mainnet/eos#108]
Since the eosio.sudo contract has been renamed eosio.wrap, why is the eosio.sudo contract still in 1.5.x

**Comment by lsf1001** [comment]
@jgiszczak  @heifner  @arhag

**Comment by jgiszczak** [comment]
`eosio.sudo` is still used in the testnet template, used by `eosio-launcher` to bootstrap a testnet automatically.
