### ISSUE TITLE
cleos --wallet-url does not work when keosd is hosted on another machine

### ISSUE THREAD

**Issue by BinaryFocus** [EOS-Mainnet/eos#21]
It seems that current logic is hard coded to check that keosd is running on the local machine even if --wallet-url specifies a URL to a remote machine. 

So something like this will fail
```
cleos --wallet-url http://{walletserver}:5555 wallet create
```
The below screenshot shows where it's hard coded.

![20180603210748 000](https://user-images.githubusercontent.com/38670376/40893762-2de13db8-6772-11e8-8d0b-3884e57a27cb.png)

**Comment by kesar** [comment]
please report to https://github.com/EOSIO/eos
