### ISSUE TITLE
failed to pin chainbase shared memory

### ISSUE THREAD

**Issue by swandoyo** [EOS-Mainnet/eos#37]
I build ok mainnet-1.0.3 this morning when I was updating my nodes. But, this afternoon, I started receiving this message when I build for new nodes:
```
CHAINBASE:   Failed to pin chainbase shared memory (of size 1024 MB) in RAM. Performance degradation is possible.
CHAINBASE:   Failed to pin chainbase shared memory (of size 340 MB) in RAM. Performance degradation is possible.
```
anyone experience the same thing?

Thanks,
Swan

**Comment by isamuelson** [comment]
same here ... running mainnet-1.0.5

**Comment by jchung00** [comment]
Could be due to a low chain db size setting in the `config.ini` file.
