### ISSUE TITLE
BUG on uint128_t, got the wrong data in the table

### ISSUE THREAD

**Issue by lhzw** [EOS-Mainnet/eos#38]
I used uint128_t, the data in the talbe on dawn-3.0 it's okay. But today I
found the table on mainnet-1.0.3 it's wrong. Then I tested my contract on
mainnet-1.0.5, mainnet-1.0.2.2 and dawn-v4.2.0, all wrong. It's fine on
dawn-v3.0.0, at first I checked the data in the table on 3.0, later I didn't
check the data carefully.
Seems the bug appears after the pretty hex format of uint128_t instead of the
ugly big number.

MY PROGRAM ONLY USES THE LOW 92 BITS.

system: ubuntu 17.10

code piece:
------------------------------------------------------------------------------
        print(" skills: ", newskills);
        pandas.emplace(code_account, [&](auto &rec)
        {
            rec.id = newpandaid;
            rec.type = newtype;
            rec.skills = newskills;
            print(" skills: ", newskills);
            print(" rec.skills: ", rec.skills);
            rec.inner_dan = dan;
        });

dawn-3.0:

nodeos's log:
skills: 6044629098178698989817856 rec.skills: 6044629098178698989817856

{
  "rows": [{
      "id": 0,
      "type": "diamond",
      "skills": "6044629098178698989817856",
      "inner_dan": 0
    },{

>>> a = '%x' % 6044629098178698989817856
>>> a
'500000000600000005000'
>>> len(a)
21

------------------------------------------------------------------------------
mainnet-1.0.5:

nodeos's log
skills: 6044629098178698989817856 rec.skills: 6044629098178698989817856

get table ouput:
{
  "rows": [{
      "panda_id": 0,
      "type": "diamond",
      "skills": "0x00500000006000000000050000000000",
      "txnid": 888,
      "success": 1,
      "inner_dan": 0
    }
  ],
  "more": false
}

>>> a = '%x' % 6044629098178698989817856
>>> len(a)
21
>>> a
'500000000600000005000'

We can see the data (6044629098178698989817856) I stored and the data
("0x00500000006000000000050000000000") I got from the table are different:
stored:            '500000000600000005000'
got:     "0x00500000006000000000050000000000"

**Comment by jchung00** [comment]
This is more suitable to file in the EOSIO/eos repository
