### ISSUE TITLE
what does "pre-release" mean?

### ISSUE THREAD

**Issue by wukoo** [EOS-Mainnet/eos#57]
I find that in Release page, MainNet-1.1.0 or 1.0.10 or 1.0.9 all with the pre-release tag.

Does it mean that we don't need to update to these versions, these versions are not stable or haven't got enough tests?

Or it does not mean anything, these versions also can be used in production.

**Comment by jchung00** [comment]
We've been following block.one's EOSIO/eos repository for those labels. We do a couple more rounds of tests before releasing tags on this mainnet repository, so should feel safer to deploy these versions into production.
