### ISSUE TITLE
Authority struct mismatch

### ISSUE THREAD

**Issue by andresberrios** [EOS-Mainnet/eos#61]
The `authority` struct defined in [contracts/eosio.system/native.hpp](https://github.com/EOS-Mainnet/eos/blob/master/contracts/eosio.system/native.hpp#L38) doesn't match the one in the actual native underlying system code in [libraries/chain/include/eosio/chain/authority.hpp](https://github.com/EOS-Mainnet/eos/blob/master/libraries/chain/include/eosio/chain/authority.hpp#L59). Specifically, they differ in `waits` vs `delay_sec`. Besides that, the internal representation of a `public_key` is also different.

These issues prevent you from calling `newaccount` (or any other action that takes an authority as parameter) as an inline action or deferred transaction, since when you instantiate these structs from contract code they won't match the ones in the native code and it will fail when deserializing them at the other end. This has been discussed a bit in the EOSIO/eos repository but nothing is clear, there are no answers after several days, and I haven't been able to find any workaround. It's not even clear to me if the "new format" for authorities is the ones using `waits` or `delay_sec`.

Related:
- https://github.com/EOSIO/eos/issues/4669
- https://github.com/EOSIO/eos/issues/4684

**Comment by andresberrios** [comment]
## Update:

Using the format with `waits` instead of `delay_sec` works well for creating a new account (`eosio::newaccount`) but sending the same authority struct to `updateauth` fails when unpacking it:

```
2018-08-03T21:44:35.123 thread-0   main.cpp:2888 main ] Failed with error: Out of Range (8)
get datastream of length 66 over by 1
Error unpacking field _storage
error unpacking fc::crypto::public_key
Error unpacking field key
error unpacking eosio::chain::key_weight
Error unpacking field keys
error unpacking eosio::chain::authority
Error unpacking field auth
error unpacking eosio::chain::updateauth
error unpacking eosio::chain::updateauth
```

**Comment by jchung00** [comment]
This should be filed directly to the EOSIO/eos repository.
